---
title: "Local Authorities in the UK with high rates or numbesr of COVID-19 cases"
author: "Analysis by Colin Angus with thanks to Francisco Rowe for helping me work GitHub Pages"
date: "12/09/2020"
output: html_document
---
```{r, include = FALSE}
library(tidyverse)
library(curl)
library(readxl)
library(ggtext)
library(paletteer)
library(lubridate)
library(forcats)
library(RcppRoll)
library(gt)
```

```{r,include= FALSE}
daydata <- read.csv("LACases.csv")[,-c(1)]
daydata$date <- as.Date(daydata$date)

```


```{r,include= FALSE}
shortcases <- daydata %>% 
  as.data.frame() %>% 
  filter(!name %in% c("England", "Wales", "Scotland", "Northern Ireland")) %>% 
  select(name, date, country, casesroll_avg, caserate_avg) %>% 
  arrange(name, date) %>% 
  group_by(name) %>% 
  mutate(cases_change=casesroll_avg-lag(casesroll_avg, 7),
         caserate_change=caserate_avg-lag(caserate_avg, 7)) %>% 
  #censor data from last 3 days due to underreporting
  slice_tail(n=4) %>% 
  slice_head(n=1) %>% 
  as.data.frame()

up_arrow <- "<span style=\"color:red\">&#9650;</span>"
down_arrow <- "<span style=\"color:green\">&#9660;</span>"

#Code for sparklines adapted from Tom Mock's excellent blog
#https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/
maxdate=max(shortcases$date)
```

```{r, include=FALSE}
#Highest case numbers
plot_spark1 <- function(data){
  data %>% 
    ggplot(aes(x = date, y = casesroll_avg)) +
    geom_line(size = 15) +
    theme_void() +
    theme(legend.position = "none")
}

sparknamedata1 <- shortcases %>% 
  slice_max(casesroll_avg, n=10)

sparknamedata1$name <- as.character(sparknamedata1$name)

sparknamedata1$name <- fct_inorder(sparknamedata1$name)

spark_plots1 <- daydata %>% 
  as.data.frame() %>% 
  filter(name %in% unique(sparknamedata1$name) & date>maxdate-months(1) & date<=maxdate-days(3)) %>% 
  select(name, date, country, casesroll_avg) %>% 
  mutate(name=factor(name, levels=unique(sparknamedata1$name))) %>% 
  arrange(name, date) %>% 
  nest(casesroll_avg = c(date, casesroll_avg)) %>% 
  mutate(plot = map(casesroll_avg, plot_spark1))

casetable <- shortcases %>% 
  slice_max(casesroll_avg, n=10) %>% 
  mutate(ggplot = NA) %>%
  gt(rowname_col="name") %>% 
  tab_header(title="Local Authorities in the UK with the highest number of new COVID cases",
             subtitle="Based on 7-day rolling average of Pillar 1 and 2 tests combined") %>% 
  tab_source_note("Data from PHE, PHW, DoHNI and ScotGov | Analysis by @VictimOfMaths") %>% 
  tab_stubhead(label="Local Authority") %>% 
  tab_spanner(label="Current cases per day", columns=vars(casesroll_avg, caserate_avg)) %>% 
  tab_spanner(label="Change in daily cases in the last 7 days", columns=vars(cases_change, caserate_change)) %>% 
  tab_footnote(footnote="Data from the most recent 3 days available is excluded as this is often very incomplete", locations=cells_column_labels(columns=vars(date))) %>% 
  cols_label(date="Data up to", country="Country", casesroll_avg="Total",
             caserate_avg="Rate per 100,000", cases_change="Total", 
             caserate_change="Rate per 100,000", ggplot="Last month") %>% 
  fmt_date(columns=vars(date), date_style=9) %>% 
  fmt_number(columns=vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             decimals=1) %>% 
  text_transform(locations=cells_body(columns="cases_change", rows=cases_change<0),
                 fn = function(x) paste(x, down_arrow)) %>% 
  text_transform(locations=cells_body(columns="cases_change", rows=cases_change>0),
                 fn = function(x) paste(x, up_arrow)) %>% 
  text_transform(
    locations = cells_body(vars(ggplot)),
    fn = function(x){
      map(spark_plots1$plot, ggplot_image, height = px(15), aspect_ratio = 4)
    }
  ) %>% 
  cols_width(vars(ggplot) ~ px(100)) %>% 
  cols_width(vars(casesroll_avg, caserate_avg, cases_change, caserate_change)
             ~ px(100)) %>% 
  cols_align(vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             align="center")
```

```{r, include=FALSE}
#Highest case rates
plot_spark2 <- function(data){
  data %>% 
    ggplot(aes(x = date, y = caserate_avg)) +
    geom_line(size = 15) +
    theme_void() +
    theme(legend.position = "none")
}

sparknamedata2 <- shortcases %>% 
  slice_max(caserate_avg, n=10)

sparknamedata2$name <- as.character(sparknamedata2$name)

sparknamedata2$name <- fct_inorder(sparknamedata2$name)

spark_plots2 <- daydata %>% 
  as.data.frame() %>% 
  filter(name %in% unique(sparknamedata2$name) & date>maxdate-months(1) & date<=maxdate-days(3)) %>% 
  select(name, date, country, caserate_avg) %>% 
  mutate(name=factor(name, levels=unique(sparknamedata2$name))) %>% 
  arrange(name, date) %>% 
  nest(caserate_avg = c(date, caserate_avg)) %>% 
  mutate(plot = map(caserate_avg, plot_spark2))

ratetable <- shortcases %>% 
  slice_max(caserate_avg, n=10) %>% 
  mutate(ggplot = NA) %>%
  gt(rowname_col="name") %>% 
  tab_header(title="Local Authorities in the UK with the highest rate of new COVID cases",
             subtitle="Based on 7-day rolling average of Pillar 1 and 2 tests combined") %>% 
  tab_source_note("Data from PHE, PHW, DoHNI and ScotGov | Analysis by @VictimOfMaths") %>% 
  tab_stubhead(label="Local Authority") %>% 
  tab_spanner(label="Current cases per day", columns=vars(caserate_avg, casesroll_avg)) %>% 
  tab_spanner(label="Change in daily cases in the last 7 days", columns=vars(caserate_change, cases_change)) %>% 
   tab_footnote(footnote="Data from the most recent 3 days available is excluded as this is often very incomplete", locations=cells_column_labels(columns=vars(date))) %>% 
  cols_label(date="Data up to", country="Country", casesroll_avg="Total",
             caserate_avg="Rate per 100,000", cases_change="Total", 
             caserate_change="Rate per 100,000", ggplot="Last month") %>% 
  fmt_date(columns=vars(date), date_style=9) %>% 
  fmt_number(columns=vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             decimals=1) %>% 
  text_transform(locations=cells_body(columns="caserate_change", rows=cases_change<0),
                 fn = function(x) paste(x, down_arrow)) %>% 
  text_transform(locations=cells_body(columns="caserate_change", rows=cases_change>0),
                 fn = function(x) paste(x, up_arrow)) %>% 
  text_transform(
    locations = cells_body(vars(ggplot)),
    fn = function(x){
      map(spark_plots2$plot, ggplot_image, height = px(15), aspect_ratio = 4)
    }
  ) %>% 
  cols_width(vars(ggplot) ~ px(100)) %>% 
  cols_width(vars(casesroll_avg, caserate_avg, cases_change, caserate_change)
             ~ px(100)) %>% 
  cols_align(vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             align="center")
```

```{r, include=FALSE}
#Biggest rise in case numbers
plot_spark3 <- function(data){
  data %>% 
    ggplot(aes(x = date, y = cases_change)) +
    geom_line(size = 15) +
    theme_void() +
    theme(legend.position = "none")
}

sparknamedata3 <- shortcases %>% 
  slice_max(cases_change, n=10)

sparknamedata3$name <- as.character(sparknamedata3$name)

sparknamedata3$name <- fct_inorder(sparknamedata3$name)

spark_plots3 <- daydata %>% 
  as.data.frame() %>% 
  arrange(name, date) %>% 
  group_by(name) %>% 
  mutate(cases_change=casesroll_avg-lag(casesroll_avg, 7)) %>% 
  ungroup() %>% 
  filter(name %in% unique(sparknamedata3$name) & date>maxdate-months(1) & date<=maxdate-days(3)) %>% 
  select(name, date, country, cases_change) %>% 
  mutate(name=factor(name, levels=unique(sparknamedata3$name))) %>% 
  nest(cases_change = c(date, cases_change)) %>% 
  mutate(plot = map(cases_change, plot_spark3))

casechangetable <- shortcases %>% 
  slice_max(cases_change, n=10) %>% 
  mutate(ggplot=NA) %>% 
  gt(rowname_col="name") %>% 
  tab_header(title="Local Authorities in the UK with biggest rise in new COVID-19 case numbers in the last week",
             subtitle="Based on 7-day rolling average of Pillar 1 and 2 tests combined") %>% 
  tab_source_note("Data from PHE, PHW, DoHNI and ScotGov | Analysis by @VictimOfMaths") %>% 
  tab_stubhead(label="Local Authority") %>% 
  cols_move(columns=vars(cases_change, caserate_change), after="country") %>% 
  tab_spanner(label="Change in last 7 days", columns=vars(cases_change, caserate_change)) %>% 
  tab_spanner(label="Change in daily cases in the last 7 days", columns=vars(casesroll_avg, caserate_avg)) %>% 
   tab_footnote(footnote="Data from the most recent 3 days available is excluded as this is often very incomplete", locations=cells_column_labels(columns=vars(date))) %>% 
  cols_label(date="Data up to", country="Country", casesroll_avg="Total",
             caserate_avg="Rate per 100,000", cases_change="Total", 
             caserate_change="Rate per 100,000", ggplot="Last month") %>% 
  fmt_date(columns=vars(date), date_style=9) %>% 
  fmt_number(columns=vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             decimals=1) %>% 
  text_transform(locations=cells_body(columns="cases_change", rows=cases_change<0),
                 fn = function(x) paste(x, down_arrow)) %>% 
  text_transform(locations=cells_body(columns="cases_change", rows=cases_change>0),
                 fn = function(x) paste(x, up_arrow)) %>% 
  text_transform(
    locations = cells_body(vars(ggplot)),
    fn = function(x){
      map(spark_plots3$plot, ggplot_image, height = px(15), aspect_ratio = 4)
    }
  ) %>% 
  cols_width(vars(ggplot) ~ px(100)) %>% 
  cols_width(vars(casesroll_avg, caserate_avg, cases_change, caserate_change)
             ~ px(100)) %>% 
  cols_align(vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             align="center")
```

```{r, include=FALSE}
#Biggest rise in case rates
plot_spark4 <- function(data){
  data %>% 
    ggplot(aes(x = date, y = caserate_change)) +
    geom_line(size = 15) +
    theme_void() +
    theme(legend.position = "none")
}

sparknamedata4 <- shortcases %>% 
  slice_max(caserate_change, n=10)

sparknamedata4$name <- as.character(sparknamedata4$name)

sparknamedata4$name <- fct_inorder(sparknamedata4$name)

spark_plots4 <- daydata %>% 
  as.data.frame() %>% 
  arrange(name, date) %>% 
  group_by(name) %>% 
  mutate(caserate_change=caserate_avg-lag(caserate_avg, 7)) %>% 
  ungroup() %>% 
  filter(name %in% unique(sparknamedata4$name) & date>maxdate-months(1) & date<=maxdate-days(3)) %>% 
  select(name, date, country, caserate_change) %>% 
  mutate(name=factor(name, levels=unique(sparknamedata4$name))) %>% 
  nest(caserate_change = c(date, caserate_change)) %>% 
  mutate(plot = map(caserate_change, plot_spark4))

ratechangetable <- shortcases %>% 
  slice_max(caserate_change, n=10) %>% 
  mutate(ggplot=NA) %>% 
  gt(rowname_col="name") %>% 
  tab_header(title="Local Authorities in the UK with biggest rise in new COVID-19 case rates in the last week",
             subtitle="Based on 7-day rolling average of Pillar 1 and 2 tests combined") %>% 
  tab_source_note("Data from PHE, PHW, DoHNI and ScotGov | Analysis by @VictimOfMaths") %>% 
  tab_stubhead(label="Local Authority") %>% 
  cols_move(columns=vars(cases_change, caserate_change), after="country") %>% 
  tab_spanner(label="Current cases per day", columns=vars(caserate_avg, casesroll_avg)) %>% 
  tab_spanner(label="Change in daily cases in the last 7 days", columns=vars(caserate_change, cases_change)) %>% 
   tab_footnote(footnote="Data from the most recent 3 days available is excluded as this is often very incomplete", locations=cells_column_labels(columns=vars(date))) %>% 
  cols_label(date="Data up to", country="Country", casesroll_avg="Total",
             caserate_avg="Rate per 100,000", cases_change="Total", 
             caserate_change="Rate per 100,000", ggplot="Last month") %>% 
  fmt_date(columns=vars(date), date_style=9) %>% 
  fmt_number(columns=vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             decimals=1) %>% 
  text_transform(locations=cells_body(columns="caserate_change", rows=cases_change<0),
                 fn = function(x) paste(x, down_arrow)) %>% 
  text_transform(locations=cells_body(columns="caserate_change", rows=cases_change>0),
                 fn = function(x) paste(x, up_arrow)) %>% 
  text_transform(
    locations = cells_body(vars(ggplot)),
    fn = function(x){
      map(spark_plots4$plot, ggplot_image, height = px(15), aspect_ratio = 4)
    }
  ) %>% 
  cols_width(vars(ggplot) ~ px(100)) %>% 
  cols_width(vars(casesroll_avg, caserate_avg, cases_change, caserate_change)
             ~ px(100)) %>% 
  cols_align(vars(casesroll_avg, caserate_avg, cases_change, caserate_change),
             align="center")
```



```{r}
casetable

ratetable

casechangetable

ratechangetable
```

